spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: &connectionUrl jdbc:mysql://localhost:3306/asset?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: &username ${DB_CONNECTION_USERNAME:root}
    password: &password ${DB_CONNECTION_PASSWORD:password}
  jpa:
    show-sql: true
    open-in-view: true
    generate-ddl: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
server:
  port : 8081

